spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhengkai02/config-repo
          username: xju_zk@163.com
          password: 122090401762.git
          basedir: /Project/sell/config/basedir
          search-paths: '{application}'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/