server:
  port: 8081
spring:
  application:
    name: oscarmall-dev-changan-v0-snapshot
  cloud:
    consul:
      host: localhost
      discovery:
        prefer-ip-address: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oscar_mall_dev_changan?characterEncoding=utf-8&useSLL=true&serverTimeZone=UTC
    username: root
    password: admin123
  redis:
    host: localhost
    port: 6379
    cluster:
      nodes: localhost:6379,localhost:6380,localhost:6381
    password:
  rabbitmq:
    host: 172.16.22.114
    username: admin
    password: admin
    virtualHost: /test
    listener:
      simple:
        acknowledge-mode: auto
changan:
  url: http://tspdemo.changan.com.cn
  appId: 8B2F79AC4C7A4F2BB71A81046EB01E47
  appKey: L6fEBGI+fIWl4JvxbWAEOPw==
  scope: cu
project:
  name: changan
  env: dev
  version: v0
errorCode:
  prefix: ""
