project:
  name: oscarMall
  env: ft
  version: v3

server:
  port: 8081

spring:
  application:
    name: offer
  cloud:
    consul:
      host: 10.45.82.76
      discovery:
        prefer-ip-address: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.45.82.76:3306/oscar_mall_offer
    username: nretail
    password: Iot$1234
  redis:
    port: 7381
    host: 10.45.66.129
    password:
    cluster:
      nodes: 10.45.66.129:7381,10.45.66.129:7382,10.45.66.129:7383,10.45.66.129:7384,10.45.66.129:7385,10.45.66.129:7386
      enabled: true
  rabbitmq:
    host: 172.16.22.114
    username: admin
    password: admin
    virtualHost: /test

# 分布式文件系统FDFS配置
fdfs:
  http_anti_steal_token: true #token 防盗链功能
  http_secret_key: FastDFS1234567890 # 密钥
  showUrl: http://172.16.22.153:80/
  soTimeout: 1500 #socket连接超时时长
  connectTimeout: 600 #连接tracker服务器超时时长
  thumbImage: #缩略图生成参数，可选
    width: 150
    height: 150
  trackerList: #TrackerList参数,支持多个，我这里只有一个，如果有多个在下方加- x.x.x.x:port :NRetail/NRetail
    - 172.16.22.153:22122
  pool:
    jmx-enabled: false
  suffix:  #配置允许附件上传的后缀
    allowUpload: bmp,jpg,png,tif,gif,pcx,tga,exif,fpx,svg,psd,cdr,pcd,dxf,ufo,eps,ai,raw,WMF,webp,avi、wmv、mpeg、mp4、mov、mkv、flv、f4v、m4v、rmvb、rm、3gp、dat、ts、mts、vob,xls,xlsx
oscar:
  rest:
    coupon:
      name: coupon
      path: /coupon
    product:
      name: oscarmall-dev-product-v0-snapshot
      path: /product
    user:
      name: oscarboss-dev-oscarbossopenapi-v0-snapshot
      path: /user
    content:
      name: oscarmall-dev-content-v0-snapshot
      path: /content

logging:
  config: code/java/config/logback.xml


es:
  enabled: true
  cluster:
    nodes: 10.45.66.129,172.16.22.51:9200,172.16.22.51