spring:
  profiles:
    #本机环境:local 开发环境:dev 测试环境:test 生产环境:prod
    active: local

mybatis-plus:
  mapperLocations: classpath:offer/mapper/*.xml

mybatis:
  configuration:
    map-underscore-to-camel-case: true


