server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sell?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: admin123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: indi.zk.mall.demo.entity
  mapper-locations: classpath:/mapper/*Dao.xml     #mybatis的mapper.xml文件文职
