spring:
  application:
    name: client
  cloud:
    consul:
      host: localhost
      discovery:
        prefer-ip-address: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oscar_mall_dev_changan?characterEncoding=utf-8&useSLL=true&serverTimeZone=UTC
    username: root
    password: admin123
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000