project:
  name: oscarMall
  env: dev
  version: v0
spring:
  application:
    name: service
  cloud:
    consul:
      host: localhost
      discovery:
        prefer-ip-address: true
  redis:
    host: localhost
    port: 6379
    password:
    cluster:
      nodes: localhost:6379,localhost:6380,localhost:6381
      enabled: true
    connectionTimeout: 10000
    soTimeout: 10000
    maxIdle: 30
    maxTotal: 30
    maxWaitMilli: 10000
    minIdle: 15
    numTestsPerEvictionRun: 3
    testOnBorrow: false
    testOnReturn: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 30000
    minEvictableIdleTimeMillis: 60000
  session:
    store-type: none
  rabbitmq:
    host: 172.16.22.114
    username: admin
    password: admin
    virtualHost: /test
changan:
  url: http://tspdemo.changan.com.cn
  appId: 8B2F79AC4C7A4F2BB71A81046EB01E47
  appKey: L6fEBGI+fIWl4JvxbWAEOPw==
  grantType: client_credentials
  scope: cu
errorCode:
  prefix: ""
oscar:
  rest:
    offer:
      name: oscarmall-dev-offer-v0-snapshot
      path: /offer
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000
