package com.iwhalecloud.retail.offer.consts;

import org.apache.commons.lang3.StringUtils;

import com.iwhalecloud.retail.common.config.ErrorCodeConfig;
import com.iwhalecloud.retail.common.consts.BaseMessageIntf;

public enum OfferBaseMessageCodeEnum implements BaseMessageIntf {

    REQUEST_IS_NULL("0001", "入参不能为空"),
    PAGE_NO_IS_NULL("0002", "当前页不能为空"),
    PAGE_SIZE_IS_NULL("0003", "每页显示条数不能为空"),
    USER_ID_IS_NULL("0004", "用户标识不能为空"),
    FILE_IS_NULL("0005", "文件不能为空"),
    GOODS_ID_IS_NULL("0006", "商品不存在"),
    THE_OFFER_ID_IS_NULL("0007", "商品不存在"),
    THE_OFFER_ID_IS_ERROR("0008", "商品不存在"),
    THE_GOOD_NOT_EXIST("0009", "商品不存在"),
    THE_GOOD_CONTENT_NOT_EXIST("0010", "商品内容不存在"),
    GOOD_STOCK_IN_DATE_OUT_ERROR("0011", "存在上架时间不在货架期内"),
    GOOD_IS_EXPIRED("0012", "商品已失效"),
    REQUEST_ID_IS_EXPIRED("0013", "交易流水不能为空"),
    CAT_TYPE_EMPTY("0014", "目录类型不能为空"),
    CAT_TYPE_ERROR("0015", "目录类型不正确"),
    CAT_NAME_EMPTY("0016", "目录名称不能为空"),
    CAT_NAME_NUM_OUT("0017", "目录名称字数超过上限"),
    CAT_NAME_ERROR("0018", "目录名称已经存在"),
    CAT_ID_EMPTY("0019", "目录标识不能为空"),
    PARAM_ERROR("0020", "参数异常"),
    CAT_NOT_EXIST("0021", "目录不存在"),
    PARENT_CAT_NOT_EXIST("0022", "父目录不存在"),
    CAT_DEL_HAS_CHILD_CAT("0023", "目录存在子目录，不能删除"),
    CAT_DEL_HAS_SALE_CAT("0024", "目录下存在销售目录，不能删除"),
    CAT_MEMS_HAS_PUBLISHED_GOODS("0025", "成员中含有已发布商品，无法删除"),
    CAT_MEMS_EMPTY("0026", "成员中没有可删除的商品，请选择"),
    STOCK_WAVE_ID_IS_NULL("0027", "标识不能为空"),
    STOCK_WAVE_ID_IS_ERROR("0028", "标识错误"),
    STOCK_IN_DATE_IS_ERROR("0029", "上架日期已经存在"),
    STOCK_IN_DATE_OUT_ERROR("0030", "上架日期不在货架期内"),
    STOCK_IN_TYPE_IS_ERROR("0031", "上架方式错误"),
    STATE_IS_ERROR("0032", "状态错误,无法操作"),
    ATTR_ID_IS_NULL("0033", "属性标识符不能为空"),
    ATTR_ID_IS_ERROR("0034", "属性标识符错误"),
    ATTR_VALUE_IS_NULL("0035", "属性值不能为空"),
    GOODS_NAME_IS_NULL("0036", "商品名称不能为空"),
    GOODS_SN_IS_NULL("0037", "商品编码不能为空"),
    PRODUCT_CODE_IS_NULL("0038", "产品编码不能为空"),
    GOODS_TYPE_IS_NULL("0039", "商品类型不能为空"),
    GOOD_SN_EXIST("0040", "商品编码已存在"),
    MANAGE_CAT_IS_NULL("0041", "管理目录不能为空"),
    SALE_CAT_IS_NULL("0042", "销售目录不能为空"),
    PROD_GOODS_REL_EXISTS("0043", "商品中含有已存在的商品关系"),
    PROD_GOODS_ID_NULL("0044", "A端商品ID或商品关系类型为空"),
    PROD_GOODS_REL_NOT_EXISTS("0045", "所要删除的商品关系不存在"),
    FILE_UPLOAD_FAIL("0046", "文件上传失败"),
    GENERATE_TOKEN_FAIL("0047", "Token生成失败"),
    SHOW_URL_EMPTY("0048", "配置项showUrl不能为空"),
    PIC_TYPE_IS_NULL("0049", "图片类别不能为空"),
    KEY_IS_NULL("0050", "标识不能为空"),
    PIC_URL_IS_NULL("0051", "图片url不能为空"),
    CONTENT_ID_IS_NULL("0052", "内容标识不能为空"),
    GOODS_CONTENT_TYPE_IS_NULL("0053", "商品内容类型不能为空"),
    GOODS_CONTENT_TYPE_NOT_EXIST("0054", "商品内容类型不存在"),
    GOODS_CONTENT_NOT_EXIST("0055", "商品内容不存在"),
    TARGET_GOODS_NOT_EMPTY("0056", "目标商品不能为空"),
    SALES_RULE_ID_IS_NULL("0057", "销售规则标识不能为空"),
    OBJ_ID_IS_NULL("0058", "销售规则对象标识不能为空"),
    CHANNEL_IS_NULL("0059", "渠道编码不能为空"),
    USER_INFO_IS_NULL("0060", "用户信息查询异常"),
    CAR_BRAND_ID_IS_NULL("0061", "车辆品牌标志为空"),
    CAR_SPEC_ID_IS_NULL("0062", "车辆规格标志为空"),
    ATTR_CODE_EXIST("0063", "属性编码已经存在"),
    PRODUCT_STOCK_NOT_ENOUGH("0064", "产品库存不足"),
    PRODUCT_NOT_EXIST("0065", "产品不存在"),
    GOODS_QTY_IS_NULL("0066", "商品数量不能为空"),
    DATE_FORMART_ERROR("0067", "日期转换错误"),
    AREA_PARENT_CODE_IS_NULL("0068", "父级行政代码为空"),
    AREA_LEVEL_IS_NULL("0069", "层级标识为空"),
    STORE_LEVEL_NAME_IS_NULL("0070", "店铺等级名称为空"),
    STORE_LEVEL_NAME_IS_EXIST("0071", "店铺等级名称已存在"),
    STORE_LEVEL_ID_IS_NULL("0072", "店铺等级标识符为空"),
    STORE_LEVEL_ID_IS_ERROR("0073", "店铺等级标识符错误"),
    STORE_LEVEL_IS_HAVE_STORE("0074", "店铺等级已绑定店铺"),
    CREATED_STAFF_ID_IS_ERROR("0075", "创建用户标识符错误"),
    UPDATE_STAFF_ID_IS_ERROR("0076", "更新用户标识符错误"),
    NAME_IS_NULL("0077", "店铺名称不能为空"),
    NAME_IS_EXIST("0078", "店铺名称已存在"),
    STORE_ID_IS_NULL("0078", "店铺标识不能为空"),
    STORE_ID_IS_ERROR("0080", "店铺标识错误"),
    STORE_STAFF_ID_IS_NULL("0081", "店主不能为空"),
    SELF_SUPPORT_FLAG_IS_NULL("0082", "是否自营店标识为空"),
    PHYSICAL_STORE_FLAG_IS_NULL("0083", "是否实体店标识为空"),
    STORE_IS_NOT_EXISTS("0084", "店铺不存在"),
    STORE_HAS_CHILD_STORE("0085", "店铺有子店铺不允许删除"),
    STORE_RULES_IS_NULL("0086", "店铺适用规则规则不能为空"),
    STORE_CATG_IS_NOT_EXISTS("0087", "店铺目录不存在"),
    STORE_CATG_HAS_CHILD_NODE("0088", "店铺目录下含有子节点"),
    STORE_CATG_HAS_EFF_GOODS("0089", "店铺目录下含有有效商品"),
    USEFULUSELESS_OBJ_TYPE_IS_NULL("0090", "对象类型不能为空"),
    USEFULUSELESS_OBJ_ID_IS_NULL("0091", "对象标志符不能为空"),
    USEFULUSELESS_OBJ_ID_IS_ERROR("0092", "对象类型或对象标志符错误"),
    USEFULUSELESS_TYPE_IS_ERROR("0093", "操作类型不能为空"),
    USEFULUSELESS_ACTION_IS_ERROR("0094", "操作动作不能为空"),
    QUEUE_IS_EMPTY("0095", "队列不能为空"),
    MESSAGE_ID_IS_NULL("0096", "消息标识不能为空"),
    TOPIC_IS_NULL("0097", "Topic不能为空"),
    EXCHANGE_IS_NULL("0098", "Exchange不能为空"),
    MESSAGE_CONTENT_IS_NULL("0099", "消息体不能为空"),
    MESSAGE_NOT_EXIST("0100", "消息不存在"),
    MESSAGE_CAN_NOT_RETRY("0101", "消息不可重处理"),
    SENSITIVE_WORDS_IS_NULL("0102", "敏感词不为空"),
    SENSITIVE_WORDS_IS_EXIST("0103", "敏感词已经存在"),
    SENSITIVE_WORDS_ID_IS_NULL("0104", "敏感词标识不为空"),
    SENSITIVE_WORDS_NOT_EXIST("0105", "敏感词不存在"),
    STORE_STATE_IS_NULL("0106", "店铺状态不能为空"),
    TBL_GOODS_BRAND_NOT_EXIST("0107", "商品品牌不存在"),
    TBL_GOODS_BRANDS_NOT_ALL_RIGHT("0108", "批量删除中含有异常状态商品品牌,或商品品牌不存在"),
    ATTR_ID_IS_NOT_EXIST("0109", "属性标识符不存在"),
    TENANT_ID_IS_NULL("0110", "租户标识不能为空"),
    TENANT_ID_IS_ERROR("0111", "租户标识错误"),
    TENANT_CAT_ID_IS_NULL("0112", "目录标识集合为空"),
    SPU_NAME_IS_NULL("0113", "SPU名称为空"),
    SPU_ID_IS_NULL("0114", "SPU标识符为空"),
    SPU_ID_IS_ERROR("0115", "SPU标识符错误"),
    UPDATE_STAFF_ID_IS_NULL("0116", "更新用户为空"),
    SKU_ID_IS_NULL("0117", "SKU标识符为空"),
    RULE_IS_NULL("0117", "规则为空"),
    SKU_ATTR_IDS_IS_NULL("0118", "SKU属性列表为空"),
    ATTR_SKU_IDS_IS_NULL("0119", "SKU属性标识符列表为空"),
    SPU_GOODS_IS_NULL("0120", "关联商品为空"),
    SPU_GOODS_IS_NOT_MATCH("0121", "关联商品SKU属性不匹配"),
    CREATED_STAFF_ID_IS_NULL("0122", "创建用户为空"),
    STATE_IS_NULL("0123", "店铺状态为空"),
    EVALUATION_OBJ_ID_IS_NULL("0124", "评价对象标识符不能为空"),
    EVALUATION_OBJ_TYPE_IS_NULL("0125", "评价对象不能为空"),
    EVALUATION_RATE_IS_NULL("0126", "评价不能为空"),
    EVALUATION_HAVE_SENSITIVE_WORDS("0127", "评价含有敏感词"),
    EVALUATION_ID_IS_ERROR("0128", "评价标识符错误"),
    EVALUATION_STATE_IS_NOT_A("0129", "有效评价才可隐藏"),
    EVALUATION_STATE_IS_NULL("0130", "审核状态不能为空"),
    EVALUATION_STATE_IS_NOT_C_AND_D("0131", "评价状态不是审核不通过或待审核"),
    EVALUATION_OBJ_TYPE_IS_ERROR("0132", "评价对象错误"),
    SPU_GOODS_IS_NOT_NULL("0133", "存在关联商品不能删除"),
    CHANNEL_CODE_HAS_EXIST("0134", "存在相同的渠道编码"),
    MGN_CAT_CAN_NOT_MOD_INVOICE_FALG("0135", "此目录不能修改开票标识"),
    SYN_CAT_FAIL("0136", "商品类目推送失败"),
    MGN_CAT_CAN_NOT_SET_INVOICE_CATG("0137", "管理目录不能配置发票类目"),
    ORG_ID_IS_NULL("0138", "机构标识符为空"),
    IS_CERTIFICATION_IS_NULL("0139", "实名认证为空"),
    USER_NAME_IS_NULL("0140", "用户名称为空"),
    RESULT_IS_NULL("0141", "审批结果为空"),
    SKU_NUM_OUT_MAX("0142", "SKU属性数量超过最大值"),
    DEVICE_TYPE_IS_NULL("0143", "设备类型不能为空"),
    ATTR_VALUE_IS_SAME("0144", "属性值不唯一"),
    GOODS_SALES_IS_NOT_MATCH("0145", "商品销售规则不匹配"),
    CHANNEL_NAME_IS_NULL("0146", "渠道名称不能为空"),
    CHANNEL_TYPE_IS_NULL("0147", "渠道类型不能为空"),
    CHANNEL_NAME_HAS_EXIST("0148", "存在相同的渠道名称"),
    BANK_NAME_IS_ERROR("0149", "银行开户名格式错误"),
    BANK_NUMBER_IS_ERROR("0150", "银行卡账号格式错误"),
    TAG_ID_IS_NULL("0151", "标签ID为空");

    private String status;

    private String message;

    private OfferBaseMessageCodeEnum(String status, String message) {
        if (StringUtils.isNotEmpty(ErrorCodeConfig.errorCodePrefix)) {
            this.status = ErrorCodeConfig.errorCodePrefix + status;
        }
        else {
            this.status = status;
        }
        this.message = message;
    }

    public String getStatus() {
        return status;
    }

    public String getMessage() {
        return message;
    }
}
